ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MEMBERSHIP_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MEMBERSHIP_ACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MEMBERSHIP_DEACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DEPARTMENT_ASSIGNED';
