"use client";

import React, { useEffect, useState, useCallback } from "react";
import Link from "next/link";
import { fetchWithAuth } from "@/lib/api-client";
import { Card, CardContent } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { Skeleton } from "@/components/ui/Skeleton";
import { EmptyState } from "@/components/ui/EmptyState";
// eslint-disable-next-line @typescript-eslint/no-unused-vars -- Next.js / React temporary strictness disable
import { FlaskConical, ChevronRight } from "lucide-react";
import { SearchBar } from "@/components/ui/SearchBar";
import { FilterPopover } from "@/components/ui/FilterPopover";
import { Button } from "@/components/ui/Button";

export default function LabReportsPage() {
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- Next.js / React temporary strictness disable
  const [reports, setReports] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [labId, setLabId] = useState<string | null>(null);
  const [search, setSearch] = useState("");
  const [filters, setFilters] = useState<Record<string, string>>({});

  const load = useCallback(async () => {
    try {
      setLoading(true);
      let lId = labId;
      if (!lId) {
        const lRes = await fetchWithAuth("/lab/memberships");
        const memberships = await lRes.json();
        if (memberships && memberships.length > 0) {
          lId = memberships[0].labId;
          setLabId(lId);
        }
      }
      
      if (lId) {
        const qs = new URLSearchParams();
        if (search) qs.set("search", search);
        if (filters.status) qs.set("status", filters.status);
        
        const res = await fetchWithAuth(`/labs/${lId}/reports?${qs.toString()}`);
        const data = await res.json();
        setReports(data.items || data || []);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }, [labId, search, filters]);

  useEffect(() => {
// eslint-disable-next-line react-hooks/set-state-in-effect -- Next.js / React temporary strictness disable
    load();
  }, [load]);

  const filterGroups = [
    {
      id: "status",
      label: "Status",
      options: [
        { label: "Lab Verified", value: "LAB_VERIFIED" },
        { label: "Hospital Created", value: "HOSPITAL_CREATED" }
      ]
    }
  ];

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Lab Reports</h1>
          <p className="text-slate-500 mt-1">Manage and search laboratory reports.</p>
        </div>
        <Link href="/lab/reports/new">
          <Button variant="primary" className="gap-2 w-full sm:w-auto">
            <FlaskConical size={16} />
            Create Report
          </Button>
        </Link>
      </div>

      <div className="flex flex-col sm:flex-row gap-3">
        <div className="flex-1">
          <SearchBar onSearch={setSearch} initialValue={search} placeholder="Search by patient name, title..." />
        </div>
        <FilterPopover groups={filterGroups} activeFilters={filters} onFilterChange={setFilters} />
      </div>

      {loading ? (
        <Skeleton className="h-24 w-full" />
      ) : reports.length === 0 ? (
        <EmptyState 
          icon={FlaskConical} 
          title={search || Object.keys(filters).length > 0 ? "No reports match your search" : "No reports found"} 
          description={search || Object.keys(filters).length > 0 ? "Try adjusting your filters or search term." : "There are no reports generated by this laboratory yet."} 
        />
      ) : (
        <div className="space-y-4">
          {reports.map(rep => (
            <Card key={rep.id} className="hover:shadow-md transition-shadow">
              <CardContent className="p-4 flex items-center justify-between">
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-xs font-bold text-teal-700">{rep.category}</span>
                    <Badge>{rep.provenanceStatus}</Badge>
                  </div>
                  <h3 className="font-semibold text-slate-900">{rep.title}</h3>
                  <p className="text-sm text-slate-500">
                    Patient: {rep.patient?.firstName} {rep.patient?.lastName}
                  </p>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
